# Generated by Django 5.2.8 on 2025-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='converted_amount',
            field=models.FloatField(default=0),
        ),
    ]
